[app]
      DB						= 	true  # true=mysql and false=postgres
      schedule_url              = "http://localhost:8000/profile/shrikar007"

[database]
	[database.mysql]
		    dialect					= "mysql"
        	username				= "root"
        	password				= "root"
        	name					= "github-api"
        	charset					= "utf8"
        	host                    ="192.168.43.106"
        	port                    ="3306"

	[database.postgres]
	    dialect                 = "postgres"
    	host                    = "localhost"
    	port					= "5432"
    	username                = "postgres"
    	name                    = "github-api"
    	password                = "root"

