[app]
      DB						= 	true  # mysql

[database]
	[database.mysql]
		    dialect					= "mysql"
        	username				= "root"
        	password				= "root"
        	name					= "github-api"
        	charset					= "utf8"

	[database.postgres]
	    dialect                 = "postgres"
    	host                    = "localhost"
    	port					= "5432"
    	username                = "postgres"
    	name                    = "github-api"
    	password                = "root"

